### ISSUE TITLE
Mixed content error

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/proposed-voting-districts#1]
The Leaflet CSS and JS are being requested from an HTTP link, so Chrome is blocking them.
https://twitter.com/waldojaquith/status/647420663771365377

**Comment by waldoj** [comment]
![hr](https://cloud.githubusercontent.com/assets/656758/10103528/6e52b6ee-6372-11e5-9006-553c7c30f4fa.png)

**Comment by bschoenfeld** [comment]
@waldoj Did you do something to force HTTPS? I've never dealt with HTTPS and github pages.

**Comment by qwo** [comment]
making it protocol independent should fix it. ill submit a PR

**Comment by bschoenfeld** [comment]
@stanzheng :+1:

**Comment by waldoj** [comment]
> Did you do something to force HTTPS?

D'oh! Yes, yes I do—I use the HTTPS Everywhere Chrome plugin. I even considered that possibility, but then saw the hard-coded `http://` link to Cloudflare and discounted the possibility. Of course, the problem wasn't that HTTPS Everywhere was rewriting requests within the page—it was that it was rewriting my request for github.io to HTTPS. I'm sorry about that.

@stanzheng, FWIW, there's no need to create protocol-independent requests. You can hard-code `https://` and that won't create a mixed-content warning. It's only when an HTTPS page requests HTTP assets that mixed content is a problem. If an HTTP requests an HTTPS asset, all is well. :)

**Comment by bschoenfeld** [comment]
@waldoj I learned something new
![](https://media0.giphy.com/media/Y2nbrJyAR6RiM/200_s.gif)
